Update create-issue.yml

diff --git a/.github/workflows/create-issue.yml b/.github/workflows/create-issue.yml
--- a/.github/workflows/create-issue.yml
+++ b/.github/workflows/create-issue.yml
@@ -57,33 +57,43 @@ jobs:
           fi
 
     - name: Enable branch protection on the main branch
-      uses: actions/github-script@v6
+      #uses: actions/github-script@v6
       env:
         GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
         REPO_OWNER: ${{ github.event.client_payload.owner }}
         REPO_NAME: ${{ github.event.client_payload.repo }}
-      with:
-        github-token: ${{ secrets.PAT_GITHUB }}
-        script: |
-          const [owner, repo] = '$REPO_OWNER/$REPO_NAME'.split('/');
-          const branch = 'main';
-          await github.request('PUT /repos/{owner}/{repo}/branches/{branch}/protection', {
-            owner: owner,
-            repo: repo,
-            branch: branch,
-            required_status_checks: {
-              strict: true,
-              contexts: []
-            },
-            enforce_admins: true,
-            required_pull_request_reviews: {
-              dismissal_restrictions: {},
-              dismiss_stale_reviews: true,
-              require_code_owner_reviews: true,
-              required_approving_review_count: 1
-            },
-            restrictions: null
-          });
+      run: |
+          # Get default branch name
+          DEFAULT_BRANCH=$(curl -s \
+            -H "Authorization: token $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME \
+            | jq -r .default_branch)
+
+          echo "Enabling branch protection for $DEFAULT_BRANCH branch"
+
+          curl -X PUT \
+            -H "Authorization: token $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/branches/$DEFAULT_BRANCH/protection \
+            -d '{
+              "required_status_checks": null,
+              "enforce_admins": true,
+              "required_pull_request_reviews": {
+                "dismissal_restrictions": {},
+                "dismiss_stale_reviews": true,
+                "require_code_owner_reviews": true,
+                "required_approving_review_count": 1
+              },
+              "restrictions": null
+            }'
+
+          if [ $? -eq 0 ]; then
+            echo "Branch protection enabled successfully."
+          else
+            echo "Failed to enable branch protection."
+            exit 1
+          fi
           
     - name: Create issue in another repository
       env:
